[project]
name = "brikk"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.12.7",
]

[tool.ruff.lint]
extend-select = ["I", "RUF022", "RUF023"]

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"